vampnet:
  vocab_size: 2048
  n_codebooks: 4
  n_conditioning_codebooks: 0
  r_cond_dim: 0
  noise_mode: mask
  embedding_dim: 1280
  n_layers: 20
  n_heads: 20
  flash_attn: false
  dropout: 0.1
  latent_dim: 128